version: '3.8'
services:
  next-build:
    build:
      context: .
      args:
        NODE_ENV: production
    command: ["yarn", "build"]

  next-start:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    command: ["yarn", "start"]

  next-dev:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "dev"]
